server:
  port: 8080

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.kbotsk.notification.Dto.OrderPlacedEvent
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    port: 587
    username: AKIA3G5A4VPTSQJNLC55
    password: BOs3Isceb8cPsrLLBGh6HHc55bcjwTAfIYO3AiV2WGYE
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: kirill.botskovoi@gmail.com