version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

volumes:
  auth_pg_data:
